#!/usr/bin/env python
import optparse
import sys
from collections import defaultdict

optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

bitext = [[sentence.lower().strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))[:opts.num_sents]]

f_count = defaultdict(int)
e_count = defaultdict(int)
fe_count = defaultdict(int)

for (n, (f, e)) in enumerate(bitext):
  for f_i in set(f):
    f_count[f_i] += 1
    for e_j in set(e):
      fe_count[(f_i,e_j)] += 1
  for e_j in set(e):
    e_count[e_j] += 1

dice = defaultdict(int)
for (k, (f_i, e_j)) in enumerate(fe_count.keys()):
  dice[(f_i,e_j)] = 2.0 * fe_count[(f_i, e_j)] / (f_count[f_i] + e_count[e_j])
  if k % 5000 == 0:
    sys.stderr.write(".")
sys.stderr.write("\n")


sys.stderr.write("Training with IBM Model 1... ")
count = 0
bitext = []
for (f,e) in zip(open(f_data), open(e_data)):
	if count < opts.num_sents:
		bitext.append([[None] + f.lower().strip().split(),e.lower().strip().split()])
	else:
		break
	count +=1
  
converge = 15
ef_count = defaultdict(float)
s_total = defaultdict(float)
t_prob = defaultdict(float)
f_total = defaultdict(float)

for (f, e) in bitext:
  for f_i in set(f):
    f_count[f_i] += 1
    for e_j in set(e):
      fe_count[(f_i,e_j)] += 1
  for e_j in set(e):
    e_count[e_j] += 1

#initializing t probs uniformly
for (f,e) in bitext:
	for e_i in e:
		for f_j in f:
			t_prob[(e_i,f_j)] = 1.0/(1+len(f_count))

while converge > 0:
	
	
	#initialize
	for (f,e) in bitext:
		for e_i in set(e):
			for f_j in set(f):
				ef_count[(e_i,f_j)] = 0
				f_total[f_j] = 0

	#normalization
	for (f,e) in bitext:
		for e_i in e:
			s_total[e_i] = 0
			for f_j in f:
				s_total[e_i]+= t_prob[(e_i,f_j)]


		#collect counts
		for e_i in e:
			for f_j in f:
				ef_count[(e_i,f_j)] += (float(t_prob[(e_i,f_j)])/s_total[e_i])
				f_total[f_j] += (float(t_prob[(e_i,f_j)])/s_total[e_i])

	for (f,e) in bitext:
		for f_i in set(f):
			for e_j in set(e):
				t_prob[(e_j,f_i)] = ef_count[(e_j,f_i)]/float(f_total[f_i])
	converge -=1

#output to ibm1.a
for (f,e) in bitext:
  for (i, f_i) in enumerate(f): 
    for (j, e_j) in enumerate(e):
      if t_prob[(e_j,f_i)] >= opts.threshold and i!= 0:
        sys.stdout.write("%i-%i " % (i-1,j))
  sys.stdout.write("\n")
